framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: false
    http_method_override: false
    serializer: { enable_annotations: false }
    validation: { enable_attributes: true }
    session: { enabled: false }