nelmio_cors:
    defaults:
        allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_methods: ["GET", "OPTIONS", "POST"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link", "Location"]
        max_age: 3600
    paths:
        "^/": ~
