version: "3.9"

services:
  php:
    build: ./docker/php
    container_name: bas-php
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: dev
      PHP_IDE_CONFIG: "serverName=php"
    depends_on:
      - db

  nginx:
    build: ./docker/nginx
    container_name: bas-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    container_name: bas-db
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: {}